"""
Django settings for electronics_store project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Retaining the original SECRET_KEY as provided by the user.
SECRET_KEY = 'django-insecure-%_fh=d220^t3=&38c*(wt38s9rlk5a4ntpsp0d5yx%&vk-3xa2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Keep this True for development

# *** ADDED/UPDATED: ALLOWED_HOSTS for local development ***
# This is crucial even if DEBUG is True, for robustness and clarity.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'corsheaders', # Keep this at the top for CORS to work correctly
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'shop'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Moved CorsMiddleware to be very early
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'electronics_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electronics_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres2', # Your current database name
        'USER': 'postgres', # Your PostgreSQL username
        'PASSWORD': 'postgres', # Your PostgreSQL password
        'HOST': 'localhost', # PostgreSQL server IP/hostname
        'PORT': '5432', # Default PostgreSQL port is 5432
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'shop.User' # Tell Django to use custom User model

# For development (allows all origins)
CORS_ALLOW_ALL_ORIGINS = False # Set to False for production, True for quick testing if needed
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Your React frontend's development URL
    "http://127.0.0.1:8000", # Also include 127.0.0.1 for consistency
    # Add any other origins where your frontend might be hosted
]
CORS_ALLOW_CREDENTIALS = True # VERY IMPORTANT: Allows cookies (including session and CSRF) to be sent cross-origin

# CSRF SETTINGS
# Ensure these are set to allow your frontend to interact
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    # Add any other origins where your frontend might be hosted
]

# *** CRITICAL FIX FOR CSRF COOKIE ACCESSIBILITY ***
# Set to None for development to allow localhost and 127.0.0.1 to share cookies.
# This tells Django to set the cookie for the host that served the page,
# which helps when frontend is on localhost:3000 and backend is on 127.0.0.1:8000.
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_DOMAIN = None

# Ensure SameSite is 'Lax' or 'None' (with Secure=True for 'None') for cross-site requests with credentials
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# IMPORTANT: Set CSRF_COOKIE_HTTPONLY to False for JavaScript to access the cookie
# Remember to set this back to True in production for enhanced security.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = "csrftoken"
SESSION_COOKIE_NAME = "sessionid"